# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Sync task-loop Codex agent TOML files into ~/.codex/agents/."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path


MANAGED_MARKER = "# Managed by task-loop plugin. Do not edit this file directly."
SOURCE_MARKER_PREFIX = "# Source: "
AGENT_NAME_FIELD = "name"


@dataclass(frozen=True)
class AgentSource:
    name: str
    source_path: Path
    dest_path: Path
    rendered: str


def plugin_root() -> Path:
    return Path(__file__).resolve().parents[1]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_agent_name(path: Path, text: str) -> str:
    try:
        data = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"{path}: invalid TOML: {exc}") from exc

    name = data.get(AGENT_NAME_FIELD)
    if not isinstance(name, str) or not name.strip():
        raise ValueError(f"{path}: missing required string field 'name'")
    return name


def is_task_loop_managed(text: str) -> bool:
    return text.startswith(MANAGED_MARKER + "\n")


def render_agent(source_path: Path, root: Path, dest_dir: Path) -> AgentSource:
    raw = read_text(source_path)
    name = parse_agent_name(source_path, raw)
    rendered_body = raw.replace("<plugin_root>", str(root))
    rendered = (
        f"{MANAGED_MARKER}\n"
        f"{SOURCE_MARKER_PREFIX}{source_path}\n"
        f"{rendered_body}"
    )
    if not rendered.endswith("\n"):
        rendered += "\n"
    return AgentSource(
        name=name,
        source_path=source_path,
        dest_path=dest_dir / source_path.name,
        rendered=rendered,
    )


def existing_agent_name(path: Path) -> str | None:
    try:
        text = read_text(path)
        return parse_agent_name(path, text)
    except (OSError, UnicodeDecodeError, ValueError):
        return None


def iter_toml_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted(path for path in directory.iterdir() if path.suffix == ".toml" and path.is_file())


def conflict_result(agent: AgentSource, path: Path, reason: str) -> dict[str, str]:
    return {
        "name": agent.name,
        "status": "conflict",
        "path": str(path),
        "reason": reason,
    }


def load_sources(root: Path, dest_dir: Path) -> list[AgentSource]:
    source_dir = root / "codex-agents"
    if not source_dir.is_dir():
        return []

    agents = [render_agent(path, root, dest_dir) for path in iter_toml_files(source_dir)]
    seen: dict[str, Path] = {}
    for agent in agents:
        if agent.name in seen:
            raise ValueError(
                f"duplicate source agent name {agent.name!r}: {seen[agent.name]} and {agent.source_path}"
            )
        seen[agent.name] = agent.source_path
    return agents


def global_conflicts(agent: AgentSource, dest_dir: Path) -> list[dict[str, str]]:
    conflicts: list[dict[str, str]] = []

    for path in iter_toml_files(dest_dir):
        try:
            text = read_text(path)
        except (OSError, UnicodeDecodeError):
            continue

        if path == agent.dest_path:
            if text != agent.rendered and not is_task_loop_managed(text):
                conflicts.append(conflict_result(agent, path, "destination_unmanaged"))
            continue

        if existing_agent_name(path) == agent.name:
            conflicts.append(conflict_result(agent, path, "duplicate_global_name"))

    return conflicts


def project_conflicts(agent: AgentSource, project_root: Path | None) -> list[dict[str, str]]:
    if project_root is None:
        return []
    if not project_root.is_dir():
        return [conflict_result(agent, project_root, "project_root_missing")]

    conflicts: list[dict[str, str]] = []
    project_agents_dir = project_root / ".codex" / "agents"
    for path in iter_toml_files(project_agents_dir):
        if existing_agent_name(path) == agent.name:
            conflicts.append(conflict_result(agent, path, "duplicate_project_name"))
    return conflicts


def current_status(agent: AgentSource) -> str:
    if not agent.dest_path.exists():
        return "installed"
    text = read_text(agent.dest_path)
    if text == agent.rendered:
        return "current"
    return "updated"


def write_agent(agent: AgentSource, status: str) -> None:
    if status == "current":
        return
    agent.dest_path.write_text(agent.rendered, encoding="utf-8")


def sync_agents(project_root_arg: str | None) -> tuple[int, dict[str, object]]:
    root = plugin_root()
    dest_dir = Path.home() / ".codex" / "agents"
    project_root = Path(project_root_arg).resolve() if project_root_arg else None

    try:
        agents = load_sources(root, dest_dir)
    except ValueError as exc:
        return 1, {"agents": [], "error": str(exc)}

    if not agents:
        return 0, {"agents": []}

    conflicts: list[dict[str, str]] = []
    for agent in agents:
        conflicts.extend(global_conflicts(agent, dest_dir))
        conflicts.extend(project_conflicts(agent, project_root))

    if conflicts:
        return 1, {"agents": conflicts}

    dest_dir.mkdir(parents=True, exist_ok=True)

    results: list[dict[str, str]] = []
    for agent in agents:
        try:
            status = current_status(agent)
            write_agent(agent, status)
        except (OSError, UnicodeDecodeError) as exc:
            results.append(
                {
                    "name": agent.name,
                    "status": "conflict",
                    "path": str(agent.dest_path),
                    "reason": f"write_failed: {exc}",
                }
            )
            continue
        results.append(
            {
                "name": agent.name,
                "status": status,
                "path": str(agent.dest_path),
            }
        )

    if any(item.get("status") == "conflict" for item in results):
        return 1, {"agents": results}
    return 0, {"agents": results}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        help="Optional repository root whose .codex/agents directory should be checked for duplicate agent names.",
    )
    args = parser.parse_args()

    exit_code, payload = sync_agents(args.project_root)
    print(json.dumps(payload, separators=(",", ":")))
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
