import importlib.util
import json
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "pre_git_hook.py"
CODEX_HOOKS = ROOT / "hooks" / "hooks.codex.json"


def load_hook_module():
    spec = importlib.util.spec_from_file_location("pre_git_hook", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(SCRIPT.parent))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    return module


def run_hook_process(payload):
    # The timeout turns a regex that backtracks without end into a test error.
    return subprocess.run(
        [sys.executable, str(SCRIPT)],
        input=json.dumps(payload),
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )


def run_hook_raw(payload):
    result = run_hook_process(payload)
    assert result.returncode == 0, f"Hook failed (exit {result.returncode}): {result.stderr}"
    return result


def run_hook(payload):
    # Commands the hook ignores produce no stdout; use run_hook_raw for those.
    return json.loads(run_hook_raw(payload).stdout)


def run_blocked_hook(payload):
    result = run_hook_process(payload)
    assert result.returncode == 2, (
        f"Hook allowed or failed open (exit {result.returncode}): {result.stderr}"
    )
    assert result.stderr.strip(), "Blocked hook must explain the denial on stderr"
    return result


def codex_payload(cmd):
    return {
        "hook_event_name": "PreToolUse",
        "tool_name": "exec_command",
        "tool_input": {"cmd": cmd},
    }


class PreGitHookTests(unittest.TestCase):
    def test_blocks_invalid_grok_branch_name(self):
        result = run_blocked_hook(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": {"command": "git switch -c grok-plugin-support"},
            }
        )

        self.assertIn("Branch name must start with one of", result.stderr)

    def test_blocks_grok_bulk_git_add(self):
        result = run_blocked_hook(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": {"command": "git add --all"},
            }
        )

        self.assertIn("Bulk git add operations are prohibited", result.stderr)

    def test_blocks_grok_attribution_in_commit(self):
        result = run_blocked_hook(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": {
                    "command": 'git commit -m "Generated with Claude Code"'
                },
            }
        )

        self.assertIn("AI tool attribution detected", result.stderr)

    def test_blocks_grok_attribution_in_pull_request_comment(self):
        result = run_blocked_hook(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": {
                    "command": 'gh pr comment 187 --body "Generated by Codex"'
                },
            }
        )

        self.assertIn("AI tool attribution detected", result.stderr)

    def test_allows_valid_grok_branch_name(self):
        result = run_hook_process(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": {"command": "git switch -c feat-187-grok-hooks"},
            }
        )

        self.assertEqual(result.returncode, 0, result.stderr)

    def test_prefers_existing_snake_case_payload_fields(self):
        result = run_hook_process(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git switch -c feat-187-grok-hooks"},
                "toolName": "run_terminal_command",
                "toolInput": {"command": "git switch -c invalid-branch"},
            }
        )

        self.assertEqual(result.returncode, 0, result.stderr)

    def test_allows_malformed_grok_tool_input(self):
        result = run_hook_process(
            {
                "hookEventName": "PreToolUse",
                "toolName": "run_terminal_command",
                "toolInput": ["git", "switch", "-c", "invalid-branch"],
            }
        )

        self.assertEqual(result.returncode, 0, result.stderr)

    def test_blocks_invalid_codex_exec_command_branch_name(self):
        result = run_blocked_hook(
            {
                "hook_event_name": "PreToolUse",
                "tool_name": "exec_command",
                "tool_input": {"cmd": "git switch -c codex-plugin-support"},
            }
        )

        self.assertIn("codex-plugin-support", result.stderr)

    # --- Issue #104: bare branch listing in a compound command ---

    def test_bare_branch_listing_in_compound_command_is_allowed(self):
        # `git branch` (no args) followed by another command must not be
        # misread as creating a branch named after the next command's token.
        result = run_hook_raw(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch\ngit status -sb"},
            }
        )
        self.assertEqual(result.stdout.strip(), "")

    def test_invalid_branch_on_same_line_still_blocked(self):
        # The cross-line fix must not weaken real same-line detection.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch badname"},
            }
        )
        self.assertIn("badname", result.stderr)

    # --- Issue #105: AI attribution in gh pr edit / comment ---

    def test_blocks_attribution_in_gh_pr_edit(self):
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'gh pr edit 1 --body "Generated with Claude Code"'},
            }
        )
        self.assertIn("AI tool attribution detected", result.stderr)

    def test_blocks_attribution_in_gh_pr_comment(self):
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'gh pr comment 1 --body "noreply@anthropic.com"'},
            }
        )
        self.assertIn("AI tool attribution detected", result.stderr)

    def test_clean_gh_pr_edit_is_allowed(self):
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'gh pr edit 1 --body "Fix typo in README"'},
            }
        )
        # Advisory message fires, but the operation is not denied.
        self.assertNotIn("hookSpecificOutput", response)
        self.assertIn("Contribution Guidelines", response.get("systemMessage", ""))

    def test_blocks_attribution_despite_spaces_and_global_flags(self):
        # The guard must survive extra whitespace and gh global flags placed
        # before the `pr` subcommand (e.g. `gh -R owner/repo pr edit`).
        for command in [
            'gh  pr  edit 1 --body "Generated with Claude Code"',
            'gh -R owner/repo pr edit 1 --body "Generated with Claude Code"',
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("AI tool attribution detected", result.stderr)

    def test_clean_git_commit_gets_advisory(self):
        # The other half of is_contribution_cmd: a clean commit is allowed with
        # the advisory, not denied or silently passed.
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'git commit -m "Fix typo in README"'},
            }
        )
        self.assertNotIn("hookSpecificOutput", response)
        self.assertIn("Contribution Guidelines", response.get("systemMessage", ""))

    def test_blocks_attribution_in_gh_pr_review(self):
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'gh pr review 1 --comment --body "Generated with Claude Code"'},
            }
        )
        self.assertIn("AI tool attribution detected", result.stderr)

    def test_blocks_attribution_in_compound_edit_then_merge(self):
        # A merge advisory must not short-circuit the attribution deny when both
        # appear in one compound command.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'gh pr edit 1 --body "Generated with Claude Code" && gh pr merge 1'},
            }
        )
        self.assertIn("AI tool attribution detected", result.stderr)

    # --- #104 regressions: rename, tabs, worktree in compound commands ---

    def test_rename_to_invalid_branch_is_blocked(self):
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch -m old-name badname"},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_rename_to_valid_branch_is_allowed(self):
        # A valid branch name emits the "good practice" advisory (non-empty
        # JSON, no deny), so run_hook is safe here — the path is not silent.
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch -m old-name feat-42-new"},
            }
        )
        self.assertNotIn("hookSpecificOutput", response)

    def test_tab_separator_is_still_detected(self):
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git switch -c\tbadname"},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_worktree_add_in_compound_uses_path_not_next_token(self):
        # Before the fix, the separator before the branch group matched the
        # newline and captured "git" from the next command. Now the worktree's
        # own path basename is used, so a valid prefix is allowed. The basename
        # is valid, so the hook emits the advisory (non-empty JSON) — run_hook
        # is safe here.
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git worktree add ../trees/feat-99-x\ngit status"},
            }
        )
        self.assertNotIn("hookSpecificOutput", response)

    # --- Issue #107: per-command parsing of compound commands ---

    def test_split_commands_is_quote_aware(self):
        split = load_hook_module().split_commands
        # Segments are returned stripped of surrounding whitespace.
        self.assertEqual(split("git branch -l; git branch x"), ["git branch -l", "git branch x"])
        self.assertEqual(split("a && b | c"), ["a", "b", "c"])
        # A separator inside double or single quotes must not create a segment.
        self.assertEqual(split('git commit -m "a; b"'), ['git commit -m "a; b"'])
        self.assertEqual(split("git commit -m 'a; b'"), ["git commit -m 'a; b'"])
        # A backslash-escaped quote must not desync quote state.
        self.assertEqual(split('git commit -m "a\\"b"; ls'), ['git commit -m "a\\"b"', 'ls'])
        # `&` inside a redirection token is not a command boundary.
        self.assertEqual(split("git status 2>&1"), ["git status 2>&1"])
        self.assertEqual(split("git checkout -b feat-1-x &>log"), ["git checkout -b feat-1-x &>log"])

    def test_listing_then_invalid_creation_in_compound_is_blocked(self):
        # The read-only listing must not mask the later invalid creation.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch -l; git branch badname"},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_valid_then_invalid_creation_in_compound_is_blocked(self):
        # An earlier valid creation must not mask a later invalid one.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git checkout -b feat-1-a && git checkout -b badname"},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_two_valid_creations_in_compound_are_allowed(self):
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git checkout -b feat-1-a && git checkout -b feat-2-b"},
            }
        )
        self.assertNotIn("hookSpecificOutput", response)

    def test_escaped_quote_does_not_mask_invalid_branch(self):
        # An escaped quote in a commit message must not desync the splitter and
        # swallow a later invalid creation into a read-only segment (#107).
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": 'git commit -m "a\\"b" ; git branch -l ; git branch badname'},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_line_continuation_does_not_mask_invalid_branch(self):
        # A backslash-newline continuation must not join two commands into one
        # segment, which would let a later valid creation mask the invalid one.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch bad \\\ngit checkout -b feat-1-x"},
            }
        )
        self.assertIn("bad", result.stderr)

    def test_first_invalid_branch_is_reported(self):
        # When several invalid branches appear, the first is surfaced; the
        # command is denied regardless of how many follow.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch bad1 && git branch bad2"},
            }
        )
        self.assertIn("bad1", result.stderr)

    def test_logical_or_separates_commands(self):
        # `||` splits on each `|`, so an invalid creation after it is caught.
        result = run_blocked_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": "git branch -l || git branch badname"},
            }
        )
        self.assertIn("badname", result.stderr)

    def test_redirection_ampersand_does_not_mask_branch_creation(self):
        # `&` in a redirection (2>&1, &>file) is not a command boundary, so an
        # invalid creation with redirected output is still caught.
        for command in [
            "git checkout -b badname 2>&1",
            "git checkout -b badname &>log",
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("badname", result.stderr)

    # --- #236 regressions: product names are not attribution ---

    def test_allows_descriptive_ai_tool_mention_in_commit(self):
        # This repository develops Claude Code and Codex plugins, so a tool
        # name in a commit message describes the change (issue #236).
        for command in [
            'git commit -m "Add a skill that backs up the global Claude Code instruction file"',
            'git commit -m "core-hooks: document the Codex CLI hook payload"',
            'git commit -m "Support Claude Code and Codex marketplace registries"',
        ]:
            with self.subTest(command=command):
                response = run_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertNotIn("hookSpecificOutput", response)
                self.assertIn(
                    "Contribution Guidelines",
                    response.get("systemMessage", ""),
                )

    def test_allows_descriptive_ai_tool_mention_in_pull_request_body(self):
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {
                    "command": 'gh pr create --title "Add Codex CLI support" --body "Ship the Claude Code hooks for the Codex CLI."'
                },
            }
        )
        self.assertNotIn("hookSpecificOutput", response)

    def test_blocks_attribution_forms(self):
        for message in [
            "Generated with [Claude Code](https://claude.com/claude-code)",
            "Created by Claude",
            "Written with Codex CLI",
            "Co-authored by Codex",
            "Co-Authored-By: Claude <claude@example.invalid>",
            "See https://claude.ai/code for details",
            "Reported-by: agent <noreply@anthropic.com>",
        ]:
            with self.subTest(message=message):
                result = run_blocked_hook(
                    {
                        "tool_name": "Bash",
                        "tool_input": {
                            "command": f'git commit -m "Fix typo" -m "{message}"'
                        },
                    }
                )
                self.assertIn("AI tool attribution detected", result.stderr)

    def test_allows_human_co_author_trailer(self):
        response = run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {
                    "command": 'git commit -m "Fix typo" -m "Co-Authored-By: Jamie Doe <jamie@example.invalid>"'
                },
            }
        )
        self.assertNotIn("hookSpecificOutput", response)
        self.assertIn(
            "Contribution Guidelines",
            response.get("systemMessage", ""),
        )

    # --- #262: only a real `git add` invocation is a bulk add ---

    def test_allows_bulk_add_text_in_heredoc_body(self):
        # A heredoc body is data, even when a line looks like a command.
        for command in [
            "python3 - <<'EOF'\nprint('git add -A')\nEOF",
            "cat > notes.md <<'EOF'\ngit add .\nEOF",
            "cat <<EOF > notes.md\ngit add --all && git add ./\nEOF\ngit status",
            # The usual commit form: a heredoc in a quoted substitution.
            "git commit -m \"$(cat <<'EOF'\nfix: explain the policy\n\ngit add -A stages every file.\nEOF\n)\"",
        ]:
            with self.subTest(command=command):
                run_hook_raw({"tool_name": "Bash", "tool_input": {"command": command}})

    def test_allows_bulk_add_text_in_quoted_argument(self):
        # A separator inside quotes does not start a command, and a quoted
        # line break does not either.
        for command in [
            'git commit -m "Block git add -A in the hook"',
            "git commit -m 'Explain why git add . is blocked'",
            'echo "stage files; git add --all"',
            'gh pr comment 1 --body "Do not run git add ./"',
            'git commit -m "Subject\ngit add -A\n"',
        ]:
            with self.subTest(command=command):
                run_hook_raw({"tool_name": "Bash", "tool_input": {"command": command}})

    def test_blocks_real_bulk_add_in_simple_and_compound_commands(self):
        for command in [
            "git add -A",
            "git add --all",
            "git add .",
            "git add ./",
            "git status && git add -A",
            "git status || git add .",
            "cd repo; git add --all",
            "echo x | git add ./",
            "git status & git add .",
            "git status\ngit add -A && git commit -m 'x'",
            "git add .>/dev/null",
            # A bulk add after a heredoc body is a real command.
            "cat <<'EOF' > notes.md\ngit add -A\nEOF\ngit add .",
            # An apostrophe in the body must not hide the command after it.
            "cat <<EOF > notes.md\ndon't stage\nEOF\ngit add -A",
            # Grouping and control keywords come before a command word.
            "(git add .)",
            "{ git add ./; }",
            "if true; then git add -A; fi",
            "for f in a; do git add .; done",
            "! git add --all",
            "time git add -A",
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Bulk git add operations are prohibited", result.stderr)

    def test_codex_exec_command_uses_the_same_bulk_add_rule(self):
        run_hook_raw(codex_payload('git commit -m "Block git add -A in the hook"'))
        result = run_blocked_hook(codex_payload("git status && git add -A"))
        self.assertIn("Bulk git add operations are prohibited", result.stderr)

    def test_allows_named_files_that_start_with_a_dot(self):
        for command in ["git add .gitignore", "git add ./src/file.py", "git add -- README.md"]:
            with self.subTest(command=command):
                run_hook_raw({"tool_name": "Bash", "tool_input": {"command": command}})

    # --- #272: only a real git command creates a branch ---

    def test_allows_branch_creation_text_in_heredoc_body(self):
        # A heredoc body is data, even when a line looks like a command.
        for command in [
            "cat > notes.md <<EOF\ngit checkout -b badname\nEOF",
            "cat > notes.md <<'EOF'\ngit switch -c badname\nEOF",
            "python3 - <<'EOF'\nrun('git worktree add trees/badname')\nEOF",
            "cat <<EOF > notes.md\ngit branch badname && git branch -m a badname\nEOF\ngit status",
        ]:
            with self.subTest(command=command):
                run_hook_raw({"tool_name": "Bash", "tool_input": {"command": command}})

    def test_allows_branch_creation_text_in_quoted_argument(self):
        # A quoted argument stays in the segment of the command that owns it.
        for command in [
            "python3 -c \"print('git checkout -b badname')\"",
            'echo "x; git checkout -b badname"',
            "gh issue create --body 'run git switch -c badname'",
            'git commit -m "Explain why git branch badname fails"',
            'git commit -m "Subject\ngit worktree add trees/badname\n"',
        ]:
            with self.subTest(command=command):
                run_hook_raw({"tool_name": "Bash", "tool_input": {"command": command}})

    def test_blocks_branch_creation_at_command_start(self):
        for command in [
            # A creation after a heredoc body is a real command.
            "cat <<'EOF' > notes.md\nhi\nEOF\ngit checkout -b badname",
            "cat <<EOF > notes.md\ndon't stop\nEOF\ngit switch -c badname",
            # A pipe or a background `&` also starts a command.
            "git status | git branch badname",
            "sleep 1 & git checkout -b badname",
            # Grouping and control keywords come before a command word.
            "(git checkout -b badname)",
            "{ git branch badname; }",
            "if true; then git switch -c badname; fi",
            "for f in a; do git worktree add trees/badname; done",
            "! git branch -m old badname",
            "time git checkout -b badname",
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Branch name 'badname' is invalid", result.stderr)

    def test_allows_valid_worktree_branch_after_options(self):
        # An option or a redirection is not the path or the commit-ish, so the
        # valid name is checked and the naming advisory fires.
        for command in [
            "git worktree add -q trees/bugfix-1-x -b bugfix-1-x",
            "git worktree add -f --lock trees/x -b feat-1-x",
            "git worktree add --lock --reason 'ci build' trees/feat-1-x",
            "git worktree add --quiet -b feat-1-x trees/x",
            "git worktree add -q trees/feat-1-x/",
            "git worktree add -q trees/feat-1-x > log.txt 2>&1",
        ]:
            with self.subTest(command=command):
                response = run_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Branch Naming Convention", response.get("systemMessage", ""))

    def test_allows_detached_worktree(self):
        # A detached worktree creates no branch.
        for command in [
            "git worktree add --detach trees/x",
            "git worktree add -d trees/x HEAD~1",
        ]:
            with self.subTest(command=command):
                result = run_hook_raw(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertEqual(result.stdout.strip(), "")

    def test_blocks_invalid_worktree_branch_after_options(self):
        for command in [
            "git worktree add -q trees/x -b badname",
            "git worktree add -q -B badname trees/feat-1-x",
            "git worktree add -q trees/badname",
            "git worktree add --lock --reason 'keep it' trees/badname",
            "git worktree add trees/badname/",
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Branch name 'badname' is invalid", result.stderr)

    def test_blocks_invalid_branch_after_git_global_options(self):
        for command in [
            "git -C /repo checkout -b badname",
            "git -C /repo switch -c badname",
            "git -C /repo worktree add trees/x -b badname",
            'git -C "my repo" branch badname',
            "git -c core.hooksPath=/dev/null checkout -b badname",
            "git --git-dir=/repo/.git --work-tree=/repo branch badname",
            "git --git-dir /repo/.git branch -m old badname",
            "git --no-pager -C /repo switch -c badname",
            "cd /repo && git -C sub checkout -b badname",
        ]:
            with self.subTest(command=command):
                result = run_blocked_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Branch name 'badname' is invalid", result.stderr)

    def test_allows_valid_branch_after_git_global_options(self):
        for command in [
            "git -C /repo checkout -b feat-1-x",
            "git -C /repo worktree add -q trees/bugfix-1-x -b bugfix-1-x",
            "git -c user.name=x switch -c doc-1-x",
        ]:
            with self.subTest(command=command):
                response = run_hook(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertIn("Branch Naming Convention", response.get("systemMessage", ""))

    def test_allows_read_only_branch_commands_after_git_global_options(self):
        for command in [
            "git -C /repo branch -l",
            "git -C /repo branch --delete feat-1-x",
            "git -C /repo checkout master",
        ]:
            with self.subTest(command=command):
                result = run_hook_raw(
                    {"tool_name": "Bash", "tool_input": {"command": command}}
                )
                self.assertEqual(result.stdout.strip(), "")

    def test_reads_many_git_global_options_quickly(self):
        # Option words that could also be option values must not make a
        # pattern that fails (here, checkout) backtrack exponentially.
        command = "git " + "-C -c --git-dir " * 30 + "branch badname"
        result = run_blocked_hook({"tool_name": "Bash", "tool_input": {"command": command}})
        self.assertIn("Branch name 'badname' is invalid", result.stderr)

    def test_codex_exec_command_uses_the_same_branch_rule(self):
        run_hook_raw(codex_payload("cat > notes.md <<'EOF'\ngit checkout -b badname\nEOF"))
        result = run_blocked_hook(codex_payload("git -C /repo checkout -b badname"))
        self.assertIn("Branch name 'badname' is invalid", result.stderr)

    def test_codex_hooks_match_exec_command_for_git_guard(self):
        hooks = json.loads(CODEX_HOOKS.read_text())
        matchers = [
            entry["matcher"]
            for entry in hooks["hooks"]["PreToolUse"]
            for hook in entry["hooks"]
            if "pre_git_hook.py" in hook["command"]
        ]

        self.assertTrue(
            any("exec_command" in matcher for matcher in matchers),
            f"pre_git_hook.py matcher should include exec_command, got {matchers}",
        )


if __name__ == "__main__":
    unittest.main()
